version: "3"
services:
  mysql:
    image: mysql:5.7
    # command: -innodb-use-native-aio=0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./.mysql:/var/lib/mysql
   
  # app:
  #   build: .
  #   container_name: app
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mysql

    
      